config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  get 'site/docs'
  get 'site/faq'
  get 'site/home'
  get 'site/docs'
  get 'home/dashboard'
  resources :servers
  resources :apps
  get 'mockup/dashboard'
  get 'mockup/app_index'
  get 'mockup/app_show'
  get 'mockup/server_index'
  get 'mockup/server_show'
  get 'mockup/jstree'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'site#index'
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :server
  store :meta, accessors: [:description, :state, :prefix]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
  # provider_type is temporal while implmenting STI
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :provider, optional: true
  store :meta, accessors: [:name, :url, :state, :description]
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_params
      params.require(:app).permit(:name, :meta, :server_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

app/controllers/mockup_controller.rb
class MockupController < ApplicationController
  def dashboard
  end

  def app_index
  end

  def app_show
  end

  def server_index
  end

  def server_show
  end

  def jstree
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def server_params
      params.require(:server).permit(:name, :provider_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def docs
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_menu(option)
    content_for :title_and_separator, "#{option} | "
    content_for :nav do
      content_tag :div, class: "hidden sm:ml-6 sm:flex" do
        (nav_link 'Dashboard', home_dashboard_path, first: true, selected: (option == :dashboard)) +
        (nav_link 'Apps', apps_path, selected: (option == :apps)) +
        (nav_link 'Servers', servers_path, selected: (option == :servers)) +
        (nav_link 'Databases', '#', selected: (option == :databases))
      end
    end
  end

  def nav_link(name, path, first: false, selected: false)
    border_color = selected ? 'indigo-500' : 'transparent'
    left_margin_class = first ? '' : 'ml-8'
    link_to name, path, class: "#{left_margin_class} inline-flex items-center px-1 pt-1 border-b-2 border-#{border_color} text-sm font-medium leading-5 text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out"
  end
  
  def description_card(title, description, &block)
    content_tag :div, class: "bg-white shadow overflow-hidden sm:rounded-lg" do
      (content_tag :div, class: "px-4 py-5 border-b border-gray-200 sm:px-6" do
        (tag.h3 title, class: "text-lg leading-6 font-medium text-gray-900") +
        (tag.p description, class: "mt-1 max-w-2xl text-sm leading-5 text-gray-500")
      end) +
      (content_tag :div, class: "px-4 py-5 sm:p-0" do
        content_tag :dl do
          capture(&block) if block_given?
        end
      end)
    end
  end

  def description_card_row(name, value, top_border: true)
    border_class = top_border ? "sm:border-t sm:border-gray-200" : ""
    content_tag :div, class: "sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 sm:py-5 #{border_class}" do
      (tag.dt name, class: "text-sm leading-5 font-medium text-gray-500") +
      (tag.dd value, class: "mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2")
    end
  end

  # TODO Research how to do it with capture and concat. I have not figure it out.
  def description_card_old(title, description, &block)
    capture do
      concat content_tag :div, class: "bg-white shadow overflow-hidden sm:rounded-lg" do
        content_tag :div, class: "px-4 py-5 border-b border-gray-200 sm:px-6" do
          concat tag.h3 title, class: "text-lg leading-6 font-medium text-gray-900"
          concat tag.p description, class: "mt-1 max-w-2xl text-sm leading-5 text-gray-500"
        end
      end
      concat content_tag :div, class: "px-4 py-5 sm:p-0" do
        content_tag :dl do
          # "inside dl".html_safe
          'algo'
        end
      end
    end
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mockup_helper.rb
module MockupHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/apps/_app.html.erb
<li class="<%= app_iteration.first? ? '' : 'border-t border-gray-200' %>">
  <a href="<%= app_path(app) %>" class="block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out">
    <div class="flex items-center px-4 py-4 sm:px-6">
      <div class="min-w-0 flex-1 flex items-center">
        <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
          <div>
            <div class="text-sm leading-5 font-medium text-indigo-600 truncate"><%= app.name %></div>
            <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"/>
                <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"/>
              </svg>
              <span class="truncate"><%= app.prefix %></span>
            </div>
          </div>
          <div class="hidden md:block">
            <div>
              <div class="text-sm leading-5 text-gray-900">
                Deployed On
                <time datetime="2020-01-07"><%= distance_of_time_in_words app.created_at %></time>
              </div>
              <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                <%= app.state %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
  </a>
</li>

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
        <% app.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :meta %>
    <%= form.text_area :meta %>
  </div>

  <div class="field">
    <%= form.label :server_id %>
    <%= form.text_field :server_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<% nav_menu(:apps) %>

<div class="bg-white shadow overflow-hidden sm:rounded-md">
  <ul>
    <li>
      <%= render partial: 'app', collection: @apps %>
    </li>
  </ul>
</div>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<% nav_menu(:apps) %>

<%= description_card @app.name, @app.description do %>
  <%= description_card_row 'Prefix', @app.prefix, top_border: false %>
  <%= description_card_row 'Deployed at', @app.created_at %>
  <%= description_card_row 'State', @app.state %>
<% end %>

app/views/home/dashboard.html.erb
<% nav_menu(:dashboard) %>

<div>
  <div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
    <div class="bg-white overflow-hidden shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <dl>
          <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
            Servers
          </dt>
          <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
            <%= Server.count %>
          </dd>
        </dl>
      </div>
    </div>
    <div class="bg-white overflow-hidden shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <dl>
          <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
            Apps
          </dt>
          <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
            <%= App.count %>
          </dd>
        </dl>
      </div>
    </div>
    <div class="bg-white overflow-hidden shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <dl>
          <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
            Providers
          </dt>
          <dd class="mt-1 text-3xl leading-9 font-semibold text-gray-900">
            <%= Provider.count %>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title_and_separator  %>RemoteDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="min-h-screen bg-gray-100">
      <nav class="bg-white shadow-sm">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between h-16">
            <div class="flex">
              <div class="flex-shrink-0 flex items-center">
                <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-on-white.svg" alt="Workflow logo">
                <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-on-white.svg" alt="Workflow logo">
              </div>
              <%= yield :nav %>
            </div>
          </div>
        </div>

        <!--
          Mobile menu, toggle classes based on menu state.

          Open: "block", closed: "hidden"
        -->
        <div class="hidden sm:hidden">
          <div class="pt-2 pb-3">
            <a href="#" class="block pl-3 pr-4 py-2 border-l-4 border-indigo-500 text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out">Dashboard</a>
            <a href="#" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out">Team</a>
            <a href="#" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out">Projects</a>
            <a href="#" class="mt-1 block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out">Calendar</a>
          </div>
          <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="flex items-center px-4">
              <div class="flex-shrink-0">
                <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </div>
              <div class="ml-3">
                <div class="text-base font-medium leading-6 text-gray-800">Tom Cook</div>
                <div class="text-sm font-medium leading-5 text-gray-500">tom@example.com</div>
              </div>
            </div>
            <div class="mt-3" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
              <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" role="menuitem">Your Profile</a>
              <a href="#" class="mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" role="menuitem">Settings</a>
              <a href="#" class="mt-1 block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 focus:outline-none focus:text-gray-800 focus:bg-gray-100 transition duration-150 ease-in-out" role="menuitem">Sign out</a>
            </div>
          </div>
        </div>
      </nav>

      <div class="py-10">
        <header>
          <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
              Dashboard
            </h1>
          </div>
        </header>
        <main>
          <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <%= yield %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/mockup/dashboard.html.erb
<div class="px-4 py-8 sm:px-0">
  <div class="border-4 border-dashed border-gray-200 rounded-lg h-96"></div>
</div>

app/views/mockup/jstree.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>jstree basic demos</title>
    <style>
        html {
            margin: 0;
            padding: 0;
            font-size: 62.5%;
        }

        body {
            max-width: 800px;
            min-width: 300px;
            margin: 0 auto;
            padding: 20px 10px;
            font-size: 14px;
            font-size: 1.4em;
        }

        h1 {
            font-size: 1.8em;
        }

        .demo {
            overflow: auto;
            border: 1px solid silver;
            min-height: 100px;
        }
    </style>

</head>

<body>

    <div id="html" class="demo">
        <ul>
            <li data-jstree='{ "opened" : true }'>Root node
                <ul>
                    <li data-jstree='{ "selected" : true }'>Child node 1</li>
                    <li>Child node 2</li>
                </ul>
            </li>
            <li data-jstree='{"opened": false}'>Folder 2</li>
        </ul>
    </div>






    <script>
        // html demo
        $('#html').jstree();
    </script>
</body>

</html>

app/views/mockup/server_index.html.erb
<h1>Mockup#server_index</h1>
<p>Find me in app/views/mockup/server_index.html.erb</p>

app/views/mockup/server_show.html.erb
<h1>Mockup#server_show</h1>
<p>Find me in app/views/mockup/server_show.html.erb</p>

app/views/servers/_aws_config_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">AWS Configuration</h3>
        <p class="mt-1 text-sm leading-5 text-gray-600">
          Configure AWS specific settings
        </p>
      </div>
    </div>
    <div class="mt-5 md:mt-0 md:col-span-2">
      <form action="#" method="POST">
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">

              <div class="col-span-6 sm:col-span-4">
                <label for="country" class="block text-sm font-medium leading-5 text-gray-700">Region</label>
                <select id="country" class="mt-1 block form-select w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                  <option>Wst Virginia (us-east-1)</option>
                  <option>Wst Virginia (us-east-1)</option>
                </select>
              </div>

              <div class="col-span-6 sm:col-span-4">
                <label for="country" class="block text-sm font-medium leading-5 text-gray-700">VPC</label>
                <select id="country" class="mt-1 block form-select w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5">
                  <option>Wst Virginia (us-east-1)</option>
                  <option>Wst Virginia (us-east-1)</option>
                </select>
              </div>

            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button class="py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 shadow-sm hover:bg-indigo-500 focus:outline-none focus:shadow-outline-blue active:bg-indigo-600 transition duration-150 ease-in-out">
              Save
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
        <% server.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meta %>
    <%= form.text_area :meta %>
  </div>

  <div class="field">
    <%= form.label :provider_id %>
    <%= form.text_field :provider_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/_separator.html.erb
<div class="hidden sm:block">
  <div class="py-5">
    <div class="border-t border-gray-200"></div>
  </div>
</div>

app/views/servers/_server.html.erb
<li class="<%= server_iteration.first? ? '' : 'border-t border-gray-200' %>">
  <a href="<%= server_path(server) %>" class="block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out">
    <div class="flex items-center px-4 py-4 sm:px-6">
      <div class="min-w-0 flex-1 flex items-center">
        <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
          <div>
            <div class="text-sm leading-5 font-medium text-indigo-600 truncate"><%= server.name %></div>
            <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"/>
                <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"/>
              </svg>
              <span class="truncate"><%= server.url %></span>
            </div>
          </div>
          <div class="hidden md:block">
            <div>
              <div class="text-sm leading-5 text-gray-900">
                Deployed On
                <time datetime="2020-01-07"><%= distance_of_time_in_words server.created_at %></time>
              </div>
              <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                <%= server.state %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
  </a>
</li>